name: Build and Deploy

on:
  push:
    branches:
      - ak-merge-upstream
  workflow_dispatch:
    inputs:
      pr_id:
        description: 'Pull Request ID'
        required: false
        default: 'manual'
        type: string
      commit_sha:
        description: 'Commit SHA to Deploy'
        required: false
        default: ''
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.upload-artifact.outputs.artifact-name }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit_sha || github.sha }}

      - name: Install Dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
        run: npm install

      - name: Build Project
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Upload to S3
        run: |
          aws s3 sync dist/client/ ${{ secrets.CLOUDFRONT_DEPLOYMENT_LOCATION }}/staging/pr${{ github.event.inputs.pr_id || 'manual' }}/ --delete
